<?php

namespace BananaStation\CoreBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;
/**
 * AvisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvisRepository extends EntityRepository {

    public function findOneByUtilisateurProjet($utilisateur, $projet) {
        $query = $this->_em->createQuery('SELECT a FROM BananaStationCoreBundle:Avis a WHERE a.utilisateur = :utilisateur AND a.projet = :projet')
            ->setParameter('utilisateur', $utilisateur)
            ->setParameter('projet', $projet)
            ->setMaxResults(1);
        try {
            return $query->getSingleResult();
        } catch (NoResultException $e) {
            return null;
        }
    }

    public function findNumberPlusme() {
        $query = $this->_em->createQuery('SELECT COUNT(a) FROM BananaStationCoreBundle:Avis a WHERE a.pouce = :pouce ORDER BY a.id DESC')
            ->setParameter('pouce','P')
            ->setMaxResults(1);
        try {
            return $query->getSingleResult()[1];
        } catch (NoResultException $e) {
            return null;
        }
    }

    public function findNumberMoisme() {
        $query = $this->_em->createQuery('SELECT COUNT(a) FROM BananaStationCoreBundle:Avis a WHERE a.pouce = :pouce ORDER BY a.id DESC')
            ->setParameter('pouce','M')
            ->setMaxResults(1);
        try {
            return $query->getSingleResult()[1];
        } catch (NoResultException $e) {
            return null;
        }
    }

}
