<?php

namespace BananaStation\CoreBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends EntityRepository
{

    public function findNumberComment() {
        $query = $this->_em->createQuery('SELECT COUNT(c) FROM BananaStationCoreBundle:Commentaire c ORDER BY c.id DESC')
            ->setMaxResults(1);
        try {
            return $query->getSingleResult()[1];
        } catch (NoResultException $e) {
            return null;
        }
    }

}
