security:
    encoders:
        BananaStation\UserBundle\Entity\Utilisateur: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_CORE, ROLE_MUSIC]
        ROLE_CORE:        ROLE_USER
        ROLE_MUSIC:       ROLE_USER

    providers:
        main:
            entity: { class: BananaStation\UserBundle\Entity\Utilisateur, property: username }

    firewalls:
        banana:
            pattern: ^/
            anonymous: true
            provider: main
            form_login:
                login_path: login
                check_path: login_check
                username_parameter: _username
                password_parameter: _password
                post_only: true
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: logout

    access_control:
        - { path: ^/account, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_CORE, host: '%host_core%' }
        - { path: ^/admin, roles: ROLE_MUSIC, host: '%host_music%' }
