swiftmailer:
    transport: '%env(MAILER_TRANSPORT)%'
    auth_mode: '%env(MAILER_AUTH_MODE)%'
    host:      '%env(MAILER_HOST)%'
    port:      '%env(MAILER_PORT)%'
    username:  '%env(MAILER_USER)%'
    password:  '%env(MAILER_PASSWORD)%'
    spool:     { type: memory }
