<?php

namespace BananaStation\UserBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends EntityRepository
{

    public function findNumberUser() {
        $query = $this->_em->createQuery('SELECT COUNT(u) FROM BananaStationUserBundle:Utilisateur u ORDER BY u.id DESC')
            ->setMaxResults(1);
        try {
            return $query->getSingleResult()[1];
        } catch (NoResultException $e) {
            return null;
        }
    }

}
