<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends EntityRepository
{
    /**
     * @return mixed|null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findLast()
    {
        $query = $this->_em->createQuery('SELECT p FROM App\Entity\Projet p ORDER BY p.id DESC')
            ->setMaxResults(1);
        try {
            return $query->getSingleResult();
        } catch (NoResultException $e) {
            return null;
        }
    }

    /**
     * @return mixed|null
     */
    public function findLastThree()
    {
        $query = $this->_em->createQuery('SELECT p FROM App\Entity\Projet p ORDER BY p.id DESC')
            ->setMaxResults(3);
        try {
            return $query->getResult();
        } catch (NoResultException $e) {
            return null;
        }
    }

    /**
     * @return mixed|null
     */
    public function findTopPlusme()
    {
        $query = $this->_em->createQuery('SELECT p, COUNT(p.id) AS HIDDEN h FROM App\Entity\Projet p, App\Entity\Avis a WHERE p = a.projet AND a.pouce = :pouce GROUP BY p.id ORDER BY h DESC, p.id DESC')
            ->setParameter('pouce', 'P')
            ->setMaxResults(3);
        try {
            return $query->getResult();
        } catch (NoResultException $e) {
            return null;
        }
    }

    /**
     * @return mixed|null
     */
    public function findTopComment()
    {
        $query = $this->_em->createQuery('SELECT p, COUNT(p.id) AS HIDDEN h FROM App\Entity\Projet p, App\Entity\Commentaire c WHERE p = c.projet GROUP BY p.id ORDER BY h DESC, p.id DESC')
            ->setMaxResults(3);
        try {
            return $query->getResult();
        } catch (NoResultException $e) {
            return null;
        }
    }
}
