<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends EntityRepository
{
    /**
     * @return null
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findNumberUser()
    {
        $query = $this->_em->createQuery('SELECT COUNT(u) FROM App\Entity\Utilisateur u ORDER BY u.id DESC')
            ->setMaxResults(1);
        try {
            return $query->getSingleResult()[1];
        } catch (NoResultException $e) {
            return null;
        }
    }

}
