banana_station_music_racine:
    pattern:  /
    host: %host_music%
    defaults: { _controller: BananaStationMusicBundle:Music:home }

banana_station_music_music_games:
    pattern:  /music/games
    host: %host_music%
    defaults: { _controller: BananaStationMusicBundle:Music:games }

banana_station_music_music_hiphop:
    pattern:  /music/hip-hop
    host: %host_music%
    defaults: { _controller: BananaStationMusicBundle:Music:hiphop }

banana_station_music_music_movies:
    pattern:  /music/movies
    host: %host_music%
    defaults: { _controller: BananaStationMusicBundle:Music:movies }

banana_station_music_music_electro:
    pattern:  /music/electro-house
    host: %host_music%
    defaults: { _controller: BananaStationMusicBundle:Music:electro }

banana_station_music_music_dubstep:
    pattern:  /music/dubstep-drum-and-bass
    host: %host_music%
    defaults: { _controller: BananaStationMusicBundle:Music:dubstep }

banana_station_music_music_rock:
    pattern:  /music/rock
    host: %host_music%
    defaults: { _controller: BananaStationMusicBundle:Music:rock }

banana_station_music_admin:
    pattern:  /admin
    host: %host_music%
    defaults: { _controller: BananaStationMusicBundle:Admin:admin }

banana_station_music_admin_add:
    pattern:  /admin/add
    host: %host_music%
    defaults: { _controller: BananaStationMusicBundle:Admin:add }

banana_station_music_admin_edit:
    pattern:  /admin/edit/{id}
    host: %host_music%
    defaults: { _controller: BananaStationMusicBundle:Admin:edit }

banana_station_music_admin_delete:
    pattern:  /admin/delete/{id}
    host: %host_music%
    defaults: { _controller: BananaStationMusicBundle:Admin:delete }

banana_station_music_page:
    pattern:  /music/page/{style}/{page}
    host: %host_music%
    defaults: { _controller: BananaStationMusicBundle:Music:page }
    requirements:
            style: g|h|m|e|d|r
            page: \d+

banana_station_music_search:
    pattern:  /music/search
    host: %host_music%
    defaults: { _controller: BananaStationMusicBundle:Music:search }