parameters:
    banana_station_music.compteur.class: BananaStation\MusicBundle\Service\Compteur
    banana_station_music.music_color.class: BananaStation\MusicBundle\Service\MusicColor

services:
    banana_station_music.compteur:
        class: "%banana_station_music.compteur.class%"
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: twig.extension }

    banana_station_music.music_color:
        class: "%banana_station_music.music_color.class%"
        tags:
            - { name: twig.extension }