parameters:
    banana_station_music.compteur.class: BananaStation\MusicBundle\Service\Compteur

services:
    banana_station_music.compteur:
        class: '%banana_station_music.compteur.class%'
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: twig.extension }