banana_station_core_racine:
    path:  /
    host: "%host_core%"
    defaults: { _controller: BananaStationCoreBundle:Home:home }

banana_station_core_about:
    path:  /about
    host: "%host_core%"
    defaults: { _controller: BananaStationCoreBundle:Other:about }

banana_station_core_project:
    path: /project/{slug}
    host: "%host_core%"
    defaults: { _controller: BananaStationCoreBundle:Project:project }

banana_station_core_projects:
    path: /projects
    host: "%host_core%"
    defaults: { _controller: BananaStationCoreBundle:Project:projects }

banana_station_core_project_edit_commentaire:
    path: /project/{id}/commentaire/edit/{idcom}
    host: "%host_core%"
    defaults: { _controller: BananaStationCoreBundle:Project:editcommentaire }

banana_station_core_project_delete_commentaire:
    path: /project/{id}/commentaire/delete/{idcom}
    host: "%host_core%"
    defaults: { _controller: BananaStationCoreBundle:Project:deletecommentaire }

banana_station_core_admin:
    path: /admin
    host: "%host_core%"
    defaults: { _controller: BananaStationCoreBundle:Admin:admin }

banana_station_core_admin_project_add:
    path: /admin/project/add
    host: "%host_core%"
    defaults: { _controller: BananaStationCoreBundle:Admin:projectadd }

banana_station_core_admin_project_edit:
    path: /admin/project/edit/{id}
    host: "%host_core%"
    defaults: { _controller: BananaStationCoreBundle:Admin:projectedit }
    requirements:
        id: \d+

banana_station_core_admin_project_delete:
    path: /admin/project/delete/{id}
    host: "%host_core%"
    defaults: { _controller: BananaStationCoreBundle:Admin:projectdelete }
    requirements:
        id: \d+

banana_station_core_admin_note_edit:
    path: /admin/note/edit/{id}
    host: "%host_core%"
    defaults: { _controller: BananaStationCoreBundle:Admin:noteedit }
    requirements:
        id: \d+

banana_station_core_admin_note_delete:
    path: /admin/note/delete/{id}
    host: "%host_core%"
    defaults: { _controller: BananaStationCoreBundle:Admin:notedelete }
    requirements:
        id: \d+