parameters:
    banana_station_core.footer.class: BananaStation\CoreBundle\Service\FooterContent
    banana_station_core.top.class: BananaStation\CoreBundle\Service\TopContent
    banana_station_core.stat.class: BananaStation\CoreBundle\Service\StatAdmin
    banana_station_core.alert.class: BananaStation\CoreBundle\Service\Alert
    banana_station_core.project_state.class: BananaStation\CoreBundle\Service\ProjectState
    banana_station_core.slugger.class: BananaStation\CoreBundle\Service\Slugger
    banana_station_core.projet_image_uploader_listener.class: BananaStation\CoreBundle\File\ProjetImageUploaderListener

services:
    banana_station_core.footer:
        class: "%banana_station_core.footer.class%"
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: twig.extension }

    banana_station_core.top:
        class: "%banana_station_core.top.class%"
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: twig.extension }

    banana_station_core.stat:
        class: "%banana_station_core.stat.class%"
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: twig.extension }

    banana_station_core.alert:
        class: "%banana_station_core.alert.class%"

    banana_station_core.project_state:
        class: "%banana_station_core.project_state.class%"
        tags:
            - { name: twig.extension }

    banana_station_core.slugger:
        class: "%banana_station_core.slugger.class%"

    banana_station_core.projet_image_uploader_listener:
        class: "%banana_station_core.projet_image_uploader_listener.class%"
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: preRemove }